name: babyname
description: Find Name For Your Baby.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # IOS icons
  cupertino_icons: ^0.1.3
  # custom icons
  font_awesome_flutter: ^8.8.1
  # database
  sqflite: ^1.3.0
  # custom alerts
  rflutter_alert: ^1.0.3
  # progress indicators
  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/boy.png"

flutter:

  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Acme
      fonts:
        - asset: fonts/Acme-Regular.ttf

